### ISSUE TITLE
项目下载下来打开什么也看不到，需要改一下哪里吗？

### ISSUE THREAD

**Issue by fishmisswater** [r00tSe7en/Flash-Pop#4]
![image](https://user-images.githubusercontent.com/11415507/169633020-9095fa68-ea74-42ad-8a2d-27d88035f4c2.png)

**Comment by r00tSe7en** [comment]
看一下网络请求，是不是有js没访问成功，可以挂个代理再访问下看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: str1ng ***@***.***&gt;
发送时间: 2022年5月21日 11:08
收件人: r00tSe7en/Flash-Pop ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [r00tSe7en/Flash-Pop] 项目下载下来打开什么也看不到，需要改一下哪里吗？ (Issue #4)

**Comment by fishmisswater** [comment]
![image](https://user-images.githubusercontent.com/11415507/169633145-f4ec80df-135c-442a-86b5-7acb0d10d1d5.png)
挂代理也是这样，但是直接请求js和css没问题

**Comment by fishmisswater** [comment]
![image](https://user-images.githubusercontent.com/11415507/169633334-0d61db23-02b1-4387-a3a0-f6ae38c3672c.png)
这里加上https:正常了

**Comment by r00tSe7en** [comment]
就是没访问到，多刷新几次，开个匿名窗口看下，还有如果你直接html文件形式打开，默认js会走file协议，你要在js链接加上https://才可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: str1ng ***@***.***&gt;
发送时间: 2022年5月21日 11:13
收件人: r00tSe7en/Flash-Pop ***@***.***&gt;
抄送: Se7en ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [r00tSe7en/Flash-Pop] 项目下载下来打开什么也看不到，需要改一下哪里吗？ (Issue #4)

**Comment by fishmisswater** [comment]
原来如此👍
